### ISSUE TITLE
issue with terraform tags

### ISSUE THREAD

**Issue by Jfeng3** [nicor88/aws-ecs-airflow#10]
cd infrastructure && terraform plan;

Error: Unsupported block type

  on network.tf line 45, in resource "aws_subnet" "public-subnet-1":
  45:     tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.

Error: Unsupported block type

  on network.tf line 62, in resource "aws_subnet" "public-subnet-2":
  62:     tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.

Error: Unsupported block type

  on network.tf line 79, in resource "aws_subnet" "public-subnet-3":
  79:     tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.

**Comment by nicor88** [comment]
@Jfeng3 which version of terraform are you using? I will try to reproduce the error.

**Comment by Jfeng3** [comment]
@nicor88 fixed by adding "=" after "tags"
