### ISSUE TITLE
Errors in infrastructure/network.tf files

### ISSUE THREAD

**Issue by NijilChandran** [nicor88/aws-ecs-airflow#18]
Error message at line no 45. 

 Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value

Just having an "=" after tags resolved the issue for me. Please update the network.tf file.
There are three such occurrence in the same file.

**Comment by nicor88** [comment]
this was due to an the fact that I used an old version of terraform were was allowed to define the tags without `=`. It's fixed now.
