### ISSUE TITLE
getting errors after creating the plugins directory

### ISSUE THREAD

**Issue by mate-hollai** [nicor88/aws-ecs-airflow#3]
worker_1     | [: CRITICAL/MainProcess] Unrecoverable error: VersionMismatch('Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6',)

What's the reason you're not using the official airflow docker image? -- why build it yourself from scratch?

**Comment by mate-hollai** [comment]
Upgrading to the suggested version fixes this...

**Comment by nicor88** [comment]
The Dockerimage used is based on [puckel/docker-airflow](https://github.com/puckel/docker-airflow) with some custom personalization. There isn't such thing as Airflow official image. All the images that you can find are custom versions.
