### ISSUE TITLE
flower error (flower doesn't start up (ie not accessible on port: 5555))

### ISSUE THREAD

**Issue by mate-hollai** [nicor88/aws-ecs-airflow#4]
worker_1     | [2019-03-07 05:50:51,945] {settings.py:174} INFO - setting.configure_orm(): Using pool settings. pool_size=10, pool_recycle=3600
flower_1     | Traceback (most recent call last):
flower_1     |   File "/usr/local/bin/flower", line 6, in <module>
flower_1     |     from flower.__main__ import main
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/__main__.py", line 4, in <module>
flower_1     |     from flower.command import FlowerCommand
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 18, in <module>
flower_1     |     from .app import Flower
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/app.py", line 15, in <module>
flower_1     |     from .urls import handlers
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/urls.py", line 9, in <module>
flower_1     |     from .api import tasks
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/api/tasks.py", line 81, in <module>
flower_1     |     class TaskApply(BaseTaskHandler):
flower_1     |   File "/usr/local/lib/python3.6/site-packages/flower/api/tasks.py", line 83, in TaskApply
flower_1     |     @web.asynchronous
flower_1     | AttributeError: module 'tornado.web' has no attribute 'asynchronous'

**Comment by nicor88** [comment]
This is related to this issue here: https://github.com/mher/flower/issues/878
